openapi: 3.0.3
info:
  title: Authentication API
  description: API for user authentication and registration
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1:8888'
paths:
  /auth:
    post:
      summary: Authenticate user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: User's username
                password:
                  type: string
                  description: User's password
              required:
                - username
                - password
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: JWT access token
                  refreshToken:
                    type: string
                    description: JWT refresh token
        '400':
          description: Invalid request data
        '401':
          description: Unauthorized - Invalid credentials
  /register:
    post:
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                username:
                  type: string
                  description: User's username
                password:
                  type: string
                  description: User's password
              required:
                - email
                - username
                - password
      responses:
        '200':
          description: Successful registration
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message
        '400':
          description: Invalid request data
        '409':
          description: Conflict - User already exists
